#!/usr/bin/env python3.8


import art_of_geom._util._debug
art_of_geom._util._debug.ON = True


from random import choice

from art_of_geom.geom.euclid._r0._point import PointR0
from art_of_geom.geom.euclid._r1.point import PointR1, PtAtInf
from art_of_geom.geom._abc._session import Session, DEFAULT_SESSION


s = Session() \
    if choice((False, True)) \
    else DEFAULT_SESSION


s.S = PointR0; print(s.S)

s.P = PointR1(name='P'); print(s.P)
s.p = PtAtInf; print(s.p)
