#!/usr/bin/env python3.8


import art_of_geom._util._debug
art_of_geom._util._debug.ON = True


from random import choice

from art_of_geom.geom.euclid._r1.point import Pt, PtAtInf
from art_of_geom.geom.session import Session, DEFAULT_SESSION


s = Session() \
    if choice((False, True)) \
    else DEFAULT_SESSION


s.P = Pt(name='P'); print(s.P)
s.p = PtAtInf; print(s.p)
