#!/usr/bin/env python3.8


from random import choice

from art_of_geom.geom.euclid.r2.point import Pt, PtAtInf
from art_of_geom.geom.euclid.r2.line import Ln, LnAtInf, Ray, Seg
from art_of_geom.geom.session import Session, DEFAULT_SESSION


s = Session() \
    if choice((True, False)) \
    else DEFAULT_SESSION


s.A = Pt(name='A'); print(s.A)
s.B = Pt(name='B'); print(s.B)
s.C = Pt(name='C'); print(s.C)
s.D = Pt(name='D'); print(s.D)


s.d = PtAtInf(s.D, name='d'); print(s.d)
s._d = PtAtInf(-s.D, name='_d'); print(s._d)


s.lnAB = Ln(s.A, s.B); print(s.lnAB)
s.lnAd = Ln(s.A, s.d); print(s.lnAd)

s.lnCD = Ln(s.C, s.D); print(s.lnCD)
s.lnCd = Ln(s.C, s.d); print(s.lnCd)


s.rayAB = Ray(s.A, s.B); print(s.rayAB)
s.rayAd = Ray(s.A, s.d); print(s.rayAd)
s.rayA_d = Ray(s.A, s._d); print(s.rayA_d)


s.segAB = Seg(s.A, s.B); print(s.segAB)
