#!/usr/bin/env bash


# *** call this script INSIDE PY3.8 VIRTUALENV and INSIDE DOC/ dir ***


MODULE=../art_of_geom
DOC_SRC_DIR=source
DOC_BUILD_DIR=_build


# remove old .RST files
rm $DOC_SRC_DIR/$MODULE*.rst

# generate .RST files from module code & docstrings
# any pathnames given at the end are paths to be excluded ignored during generation
sphinx-apidoc \
  --force \
  --implicit-namespaces \
  --maxdepth 9 \
  --module-first \
  --output-dir $DOC_SRC_DIR \
  --private \
  $MODULE


# remove old doc
rm -rf $DOC_BUILD_DIR

# build new doc
sphinx-autobuild \
  --delay 5 \
  --open-browser \
  --poll \
  --watch $DOC_SRC_DIR \
  $DOC_SRC_DIR $DOC_BUILD_DIR
