name: Install Package & Dependencies

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - 3.12
          - 3.13.0-alpha.1
          # github.com/actions/python-versions/blob/main/versions-manifest.json

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Linux Dependencies
        run: >
          sudo apt install --yes
          libpango1.0-dev

      - name: PIP-Install Package & Dependencies
        run: make install-editable
