name: Install Package & Dependencies, Lint Code and Run Tests on Mac

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  install-lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - 3.13
          # github.com/actions/python-versions/blob/main/versions-manifest.json

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: PIP-Install Package & Dependencies
        run: make install-editable

      - name: Run Tests
        run: make test-run
